spring:
  application:
    name: service-auth
  redis:
    host: 116.62.205.255
    port: 56379
    database: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.205.255:63306/auth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: J@^S%TCE9dTXusVC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9098/oauth/token_key
    client:
      client-id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:9098/oauth/token
      grant-type: password
      scope: server
      user-authorization-uri: http://localhost:9098/oauth/authorize