spring:
  application:
    name: service-auth
  redis:
    host: 116.62.205.255
    port: 56379
    database: 0
server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/